FROM python:3.10

# Install build-essential and other required dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory to /code
WORKDIR /code
# Create the /code/app directory in the container
RUN mkdir -p /code/app
# Copy the requirements.txt file and install the Python dependencies
COPY ./requirements.txt /code/
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Copy the entire app directory into the container
COPY ./main.py /code/app

# Set the working directory to /code/app
WORKDIR /code/app

# Use CMD to specify the command to run when the container starts
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
