{
 "title": "Fast API Metrics POC",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "General Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"fastapi\"}"
    }
   ]
  },
  {
   "title": "Response Success Rates",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{status=\"2xx\"}) / sum(http_requests_total) * 100",
     "legendFormat": "Overall Success Rate"
    },
    {
     "expr": "sum(http_requests_total{status=\"5xx\"}) / sum(http_requests_total) * 100",
     "legendFormat": "Server Error Rate"
    },
    {
     "expr": "sum(http_requests_total{status=\"4xx\"}) / sum(http_requests_total) * 100",
     "legendFormat": "Client Error Rate"
    }
   ]
  },
  {
   "title": "Requests / s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Log Errors / Warnings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate({job=\"fast-api-logs\", level=\"ERROR\"} [$__range]))",
     "legendFormat": "ERRORS"
    },
    {
     "expr": "count(rate({job=\"fast-api-logs\", level=\"WARNING\"} [$__range]))",
     "legendFormat": "WARNINGS"
    }
   ]
  },
  { "title": "Requests Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Requests / s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_requests_total{job=\"fastapi\"}[1m]))",
     "legendFormat": "Requests / s"
    }
   ]
  },
  {
   "title": "Requests Status",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{status=\"2xx\"})",
     "legendFormat": "Successful Requests"
    },
    {
     "expr": "sum(http_requests_total{status=\"5xx\"})",
     "legendFormat": "Server Errors"
    },
    {
     "expr": "sum(http_requests_total{status=\"4xx\"})",
     "legendFormat": "Client Errors"
    }
   ]
  },
  {
   "title": "Requests by type",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(http_requests_total[$__interval]))",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "sum(http_requests_total{method=\"GET\"})",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(http_requests_total{method=\"POST\"})",
     "legendFormat": "POST"
    },
    {
     "expr": "sum(http_requests_total{method=\"PUT\"})",
     "legendFormat": "PUT"
    },
    {
     "expr": "sum(http_requests_total{method=\"DELETE\"})",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Percent of 500 Responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{status=~\"2xx\"}) / sum by(handler) (http_requests_total)"
    }
   ]
  },
  {
   "title": "Percent of 200 Responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{status=~\"2xx\"}) / sum by(handler) (http_requests_total)"
    }
   ]
  },
  {
   "title": "Percent of 400 errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{status=~\"4xx\"}) / sum by(handler) (http_requests_total)"
    }
   ]
  },
  {
   "title": "Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum (rate(http_requests_total[1m]))",
     "legendFormat": "Requests/s"
    }
   ]
  },
  {
   "title": "AVG Request duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"fastapi\"} / http_request_duration_seconds_count{job=\"fastapi\"}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "{job=\"fast-api-logs\"}"
    }
   ]
  }
 ]
}